.vscode/launch.json
=> Introdcues launch.json including "Debug Jest Tests" script

.vscode/launch.json, data/slds/line_simpleline.sld, data/slds/point_simplepoint.sld, data/slds/point_simplepoint_filter.sld, data/slds/point_styledlabel.sld, data/slds/polygon_transparentpolygon.sld, package-lock.json, package.json, src/SldStyleParser.spec.ts, src/SldStyleParser.ts, tsconfig.json
This introduces a very basic support for reading SLD styles.
It requires a new release of geostyler-style to be mergeable.
=> Introduces readStyle implementation for basicSupprt for SLD files

data/slds/point_simplepoint_filter.sld, data/styles/point_simplepoint_filter.ts, data/xml2jsObjects/line_simpleline.json, data/xml2jsObjects/point_simplepoint.json, data/xml2jsObjects/point_simplepoint_filter.json, data/xml2jsObjects/point_styledlabel.json, data/xml2jsObjects/polygon_transparentpolygon.json, src/SldStyleParser.spec.ts, src/SldStyleParser.ts, tsconfig.json
This introduces a very basic support for wrtiting SLD styles.
=> Introduces writeStyle implementation for basicSupprt for SLD files

data/slds/point_simplepoint_filter.sld, data/styles/point_simplepoint_filter.ts, data/xml2jsObjects/point_simplepoint_filter.json, src/SldStyleParser.ts
fixes https://github.com/terrestris/geostyler-sld-parser/issues/10
I changed line breaking from CRLF to LF in the SLD, thats why the diff is huge.
=> Fix propertyIsNull Filter

package.json, src/SldStyleParser.ts
=> Fix typescript and improve lint script

data/slds/point_simplepoint_filter.sld, data/styles/point_simplepoint_filter.ts, data/xml2jsObjects/point_simplepoint_filter.json, src/SldStyleParser.ts
This fixes the SLD output to be valid by fixing the issues found in https://github.com/terrestris/geostyler/issues/123
=> Fixup SLD validity when writing SLD

package.json
=> fix(package): update @types/lodash to version 4.14.112

package.json
=> fix(package): update @types/lodash to version 4.14.116

data/styles/line_graphicStroke.ts, data/styles/line_graphicStroke_externalGraphic.ts, data/styles/line_perpendicularOffset.ts, data/styles/line_simpleline.ts, data/styles/multi_simplelineLabel.ts, data/styles/point_externalgraphic.ts, data/styles/point_simplecross.ts, data/styles/point_simplepoint.ts, data/styles/point_simplepoint_filter.ts, data/styles/point_simplepoint_nestedLogicalFilters.ts, data/styles/point_simplesquare.ts, data/styles/point_simplestar.ts, data/styles/point_simpletriangle.ts, data/styles/point_simplex.ts, data/styles/point_styledlabel.ts, data/styles/polygon_transparentpolygon.ts, package.json, src/SldStyleParser.spec.ts, src/SldStyleParser.ts
was merged.
Update code to changes in above mentioned PR. 
Also, rename functions where multiple symbolizers will be parsed. Update tests and testfiles accordingly.
=> Rename symbolizer to symbolizers

data/slds/point_styledlabel.sld, data/styles/point_styledlabel.ts, data/xml2jsObjects/point_styledlabel.json, src/SldStyleParser.ts
=> Parse Halo and Rotation of TextSymbolizer

data/slds/point_simpleslash.sld, data/styles/point_simplecross.ts, data/styles/point_simpleslash.ts, data/styles/point_simplesquare.ts, data/styles/point_simplestar.ts, data/styles/point_simpletriangle.ts, data/xml2jsObjects/point_simpleslash.json, package.json, src/SldStyleParser.spec.ts, src/SldStyleParser.ts
was merged.
Now parsing additional WellKnownNames defined by geoserver. Updated parser to new geostyler-style definitions. Also added and updated tests and testfiles.
=> Parse geoserver-specific WellKnownName

.gitignore, browser-build.config.js, package.json, src/SldStyleParser.ts, tsconfig.build.json, tsconfig.json
=> Create browser build

package.json
=> chore(package): update @types/jest to version 23.3.6

browser-build.config.js, package.json
=> Adds babel polyfill for IE support

data/styles/line_graphicFill.ts, data/styles/line_graphicStroke.ts, data/styles/point_simplecross.ts, data/styles/point_simplepoint.ts, data/styles/point_simplepoint_filter.ts, data/styles/point_simplepoint_nestedLogicalFilters.ts, data/styles/point_simpleslash.ts, data/styles/point_simplesquare.ts, data/styles/point_simplestar.ts, data/styles/point_simpletriangle.ts, data/styles/point_simplex.ts, src/SldStyleParser.ts
This solves the wrong calculation of radius/size: https://github.com/terrestris/geostyler/issues/528
=> Doubles/Halves radius/size when reading/writing to size/radius

README.md
Title says it all.
Please review.
=> Fix a typo, add more info and add a npm badge

package.json
=> chore(package): update ts-jest to version 23.10.4

src/SldStyleParser.ts
This fixes a couple of bugs in the SLD reader and writer. Also adds support for `SvgParameter`s, thus enabling reading SLD/SE 1.1.0 files.
@terrestris/devs Please review.
=> Fix sld parser

README.md
=> Fix variable name in readme

package.json, tsconfig.build.json
=> Adds flag to create .d.ts file

src/SldStyleParser.ts
@terrestris/devs Please review.
=> Filter empty properties when exporting line symbolizer

package.json, src/SldStyleParser.ts
=> Updates geostyler-style

package.json
=> Update package.json to v1.0.0

index.d.ts, package.json, tsconfig.json
This fixes/introduces the configuration for the TypeScript declaration.
=> Fixes declaration files

package-lock.json, package.json
This updates several dependencies.
closes #259
closes #261
closes #262
=> Updates several packages

package-lock.json, package.json, src/SldStyleParser.ts
This updates `geostyler-style` to v3.
=> Updates geostyler-style to v3

.eslintignore, browser-build.config.js, package-lock.json, package.json, tsconfig.json
This updates `ts-loader` to the latest version and fixes the browserbuild.
=> Updates ts-loader and fixes browserbuild

babel.config.js, data/slds/1.0/point_styledLabel_elementOrder.sld, data/slds/1.1/point_styledLabel_elementOrder.sld, data/styles/multi_simplelineLabel.ts, data/styles/point_simpleLabel.ts, data/styles/point_styledLabel_elementOrder.ts, data/styles/point_styledLabel_literalPlaceholder.ts, data/styles/point_styledlabel.ts, src/SldStyleParser.ts
Also adds another fix needed for the browser build.
@geostyler/devs Please review.
=> Add support for text opacity

src/SldStyleParser.ts
@geostyler/devs Please review.
=> Implement parsing of between filters

data/slds/1.0/point_simplepoint_filter.sld, data/slds/1.1/point_simplepoint_filter.sld, data/styles/point_simplepoint_filter.ts, src/SldStyleParser.ts
=> Write PropertyIsBetween operator

.github/workflows/on-pull-request.yml, data/slds/1.1/point_simplepoint_categorizefunctionfilter.sld, data/styles/point_simplepoint_categorizefunctionfilter.ts, data/styles/polygon_expression.ts, index.d.ts, package-lock.json, package.json, src/SldStyleParser.ts, src/SldStyleParser.v1.0.spec.ts, src/SldStyleParser.v1.1.spec.ts, src/SymbologyEncoder.ts
=> Expressions

package.json
As per #677 - note that IE is not supported
=> List IE as not supported

package.json
=> replace https git url with ssh for npm run release

src/SldStyleParser.ts
This readds the parsing of a rules `Title` tag.
=> Readd parsing of rule title

README.md
=> Remove outdated badges & add badge for GH action

src/SldStyleParser.ts
=> fix: actually set xmlns on filter

package-lock.json, package.json, src/SldStyleParser.ts
This updates the fast-xml-parser to its latest version.
Fixes #951
=> Updates fast-xml-parser

data/slds/geoserver/poi.sld, data/styles/geoserver/poi.ts, src/SldStyleParser.ts
=> feat: add displacement from point offset for geoserver

package-lock.json, package.json, src/SldStyleParser.ts, src/Util/SldUtil.ts
Test are not passing anymore. Use geostyler-style v10.2.0 to fix it
=> fix: use geostyler-style 10.2 to fix build
