geostyler/geostyler-sld-parser

- .vscode/launch.json
- data/styles/line_simpleline.ts
- data/styles/point_simplepoint.ts
- data/styles/point_simplepoint_filter.ts
- data/styles/point_styledlabel.ts
- data/styles/polygon_transparentpolygon.ts
- src/SldStyleParser.spec.ts
- src/SldStyleParser.ts
This adds some enhancements to the `readStyle` method of the SLD parser.
Further on it ...
- Adds some example styles for the corresponding SLDs to give the tests much more value.
- Introduces a jest debug config for Windows
> This adds some enhancements to the readStyle functionality

- data/slds/line_simpleline.sld
- data/slds/point_simplepoint.sld
- data/slds/point_simplepoint_filter.sld
- data/slds/point_styledlabel.sld
- data/slds/polygon_transparentpolygon.sld
- data/styles/line_simpleline.ts
- data/styles/point_simplepoint.ts
- data/styles/point_simplepoint_filter.ts
- data/styles/point_styledlabel.ts
- data/styles/polygon_transparentpolygon.ts
- package-lock.json
- package.json
- src/SldStyleParser.ts
This adds read and write logic for parsing the name property for GeoStyler Style `Style` and `Rule`.
>  Adapt parser to read and write name properties for Style and Rule

- package.json
- tsconfig.build.json
This fixes the build or the wrong name reference by adding a separate `tsconfig.build.json` with more specific excludes.
Fixes: https://github.com/terrestris/geostyler/issues/106
> This fixes the build / the wrong main reference

- data/slds/point_externalgraphic.sld
- data/styles/point_externalgraphic.ts
- data/xml2jsObjects/point_externalgraphic.json
- src/SldStyleParser.spec.ts
- src/SldStyleParser.ts
For the moment, the `format` parameter of externalgraphics is hardcoded, see issue https://github.com/terrestris/geostyler/issues/122
> Added support for ExternalGraphic in PointSymbolizer

- data/slds/point_simplepoint_filter.sld
- data/styles/point_simplepoint_filter.ts
- data/xml2jsObjects/point_simplepoint_filter.json
- src/SldStyleParser.ts
Until now, the last provided comparison operator was written to filter XML (only if it is not nested in a logical operator). This PR fixes this on order to create filters e.g. having multiple `PropertyIsLike` checks:
```
<And>
<PropertyIsLike wildCard="*" singleChar="." escape="!">
<PropertyName>TEST2</PropertyName>
<Literal>*York*</Literal>
</PropertyIsLike>
<PropertyIsLike wildCard="*" singleChar="." escape="!">
<PropertyName>TEST1</PropertyName>
<Literal>*New*</Literal>
</PropertyIsLike>
...
</And>
```
> Fix creation of Filter elements that have the same type

- data/slds/point_simplepoint_nestedLogicalFilters.sld
- data/styles/point_simplepoint_nestedLogicalFilters.ts
- data/xml2jsObjects/point_simplepoint_nestedLogicalFilters.json
- package.json
- src/SldStyleParser.spec.ts
- src/SldStyleParser.ts
This PR fixes `getSldFilterFromFilter` method that currently doesn't support multiple logical filter operations on the same level, e.g.
```
<And>
<Or>
<PropertyIsEqualTo>
<PropertyName>ID</PropertyName>
<Literal>1</Literal>
</PropertyIsEqualTo>
<PropertyIsEqualTo>
<PropertyName>ID</PropertyName>
<Literal>2</Literal>
</PropertyIsEqualTo>
</Or>
<Or>
<PropertyIsEqualTo>
<PropertyName>STREET</PropertyName>
<Literal>Main</Literal>
</PropertyIsEqualTo>
<PropertyIsEqualTo>
<PropertyName>STREET</PropertyName>
<Literal>Time square</Literal>
</PropertyIsEqualTo>
<And>
<PropertyIsGreaterThanOrEqualTo>
<PropertyName>HOUSENO</PropertyName>
<Literal>1909</Literal>
</PropertyIsGreaterThanOrEqualTo>
<PropertyIsLessThanOrEqualTo>
<PropertyName>HOUSENO</PropertyName>
<Literal>19909</Literal> …
```
> Fix use case for filters with deeply nested logical operations

- package.json
- src/SldStyleParser.ts
This changes `name` to static `title` due to changes in GeoStyler-Style v0.6.0.
> Rename 'name' to 'title' and fix assignment

- data/slds/polygon_transparentpolygon.sld
- data/styles/polygon_transparentpolygon.ts
- data/xml2jsObjects/polygon_transparentpolygon.json
- package.json
- src/SldStyleParser.ts
This adds reading and writing capabilities for the CSS parameters `stroke-width` and `stroke-dasharray` in `FillSymbolizers`.
> Parse more CSS parameters for FillSymbolizer

- data/slds/line_simpleline.sld
- data/styles/line_simpleline.ts
- data/xml2jsObjects/line_simpleline.json
- src/SldStyleParser.ts
This fixes the parsing of the 'stroke-dasharray' from an SLD. It's received as a string and has to be split and parsed into a number.
> Fixes the parsing of the SLD "stroke-dasharray"

- src/SldStyleParser.ts
This changes the way of importing lodash methods.
Before, we had
```
import {
isString as _isString,
isNumber as _isNumber,
get as _get
} from 'lodash';
```
Which lead to the following code after compiling with `tsc`:
`var lodash_1 = require("lodash");`
This leads to an include of the complete library when this module is used and build in parent projects.
After changing the code to
```
const _isString = require('lodash/isString');
const _isNumber = require('lodash/isNumber');
const _get = require('lodash/get');
```
We get the follwoing compiled output:
```
var _isString = require('lodash/isString');
var _isNumber = require('lodash/isNumber');
var _get = require('lodash/get');
```
which effectively will reduce the bundle size of parents by a few hundred kilobytes
> Optimize imports of loadsh

- data/slds/line_graphicStroke.sld
- data/slds/line_graphicStroke_externalGraphic.sld
- data/slds/line_perpendicularOffset.sld
- data/slds/line_simpleline.sld
- data/styles/line_graphicStroke.ts
- data/styles/line_graphicStroke_externalGraphic.ts
- data/styles/line_perpendicularOffset.ts
- data/styles/line_simpleline.ts
- data/xml2jsObjects/line_graphicStroke.json
- data/xml2jsObjects/line_graphicStroke_externalGraphic.json
- data/xml2jsObjects/line_perpendicularOffset.json
- data/xml2jsObjects/line_simpleline.json
- package.json
- src/SldStyleParser.spec.ts
- src/SldStyleParser.ts
**Important:** Please wait with merging this PR until 
was merged.
`stroke-linecap`, `stroke-linejoin`, `perpendicularOffset`, `stroke-dashoffset`, `graphic-stroke`, will now be parsed. Tests and tesfiles were updated accordingly.
> Include LineSymbolizer changes in parser

- data/slds/polygon_graphicFill.sld
- data/slds/polygon_graphicFill_externalGraphic.sld
- data/styles/polygon_graphicFill.ts
- data/styles/polygon_graphicFill_externalGraphic.ts
- data/xml2jsObjects/polygon_graphicFill.json
- data/xml2jsObjects/polygon_graphicFill_externalGraphic.json
- package.json
- src/SldStyleParser.spec.ts
- src/SldStyleParser.ts
was merged.
`graphicFill` of FillSymbolizer will now be parsed.
Updated tests and testfiles accordingly.
> FillSymbolizer graphicFill

- data/slds/point_externalgraphic_svg.sld
- data/styles/point_externalgraphic_svg.ts
- data/xml2jsObjects/point_externalgraphic_svg.json
- src/SldStyleParser.spec.ts
- src/SldStyleParser.ts
With this PR, `Format` tag of SLDs `ExternalGraphic` will be parsed. geostyler-style and all other parsers and Components remain the same. Also, create new `getIconSymbolizerFromSldSymbolizer()` to keep code easier to read.
Supported mime-types are:
`image/png` `image/jpeg` `image/gif` `image/svg+xml`
> Parse Format of ExternalGraphic

- src/SldStyleParser.ts
The sldSchema defines the ordering of elements. This might lead to unexpected behaviour in case the ordering differs from the definition. This PR rearranges the elements to be sldSchema conform.
Also now parsing opacity of iconSymbolizer.
> Order sld elements

- src/SldStyleParser.ts
Geostyler does not explicitly set the element `WellKnownName` of a graphic for its default value `square`. This PR handles this through explicitly setting `WellKnownName` to `square`, if it is missing.
> Handle default wellknownname

- data/slds/point_styledLabel_literalPlaceholder.sld
- data/styles/multi_simplelineLabel.ts
- data/styles/point_styledLabel_literalPlaceholder.ts
- data/xml2jsObjects/point_styledLabel_literalPlaceholder.json
- package.json
- src/SldStyleParser.spec.ts
- src/SldStyleParser.ts
was merged.
With this PR it is possible to parse templates for TextSymbolizers. Simple text will be parsed as static text. Text in double curly braces (`{{}}`) will be interpreted as feature property. Combinations are possible.
Examples:
```
hello world
--> every feature will display the text 'hello world'
```
```
hello {{world}}
--> every feature will display the text 'hello ',
appended by the value of its property "world"
```
More examples can be found in the comments.
> Parse TextSymbolizer templates

- package.json
Ass we don't want to update webpack to v4 this adds a greenkeeper (ignore) section to the package.json.
> Adds greenkeeper-ignore to package.json

- dev-build.config.js
- package.json
- src/SldStyleParser.ts
- tsconfig.build.json
- tsconfig.json
Adds a dev build and fixes reexporting previously imported styles which may have keys set with undefined/null values.
@terrestris/devs Please review.
> Add dev build, fix reexport

- data/slds/point_simplepoint_filter.sld
- data/styles/point_simplepoint_filter_forceBools.ts
- data/styles/point_simplepoint_filter_forceNumerics.ts
- data/styles/point_simplepoint_nestedLogicalFilters.ts
- data/xml2jsObjects/point_simplepoint_filter_forceBools.json
- data/xml2jsObjects/point_simplepoint_filter_forceNumerics.json
- src/SldStyleParser.spec.ts
- src/SldStyleParser.ts
This ensures that string values containing numeric values in a filter are not parsed as numeric by default. Otherwise the filter might not be correct since we do not know if the string is intended or not.
The intended parsing of certain fields can be forced by setting a list of fields (`numericFilterFields`), which will be tried to parse as numerics.
> Make parsing float values in filter optional

- src/SldStyleParser.ts
Properly generate a `fill-opacity` css param in case it's value is zero.
@terrestris/devs Please review.
> Fix handling of zero opacity

- data/styles/multi_simplelineLabel.ts
- data/styles/point_styledLabel_literalPlaceholder.ts
- data/styles/point_styledlabel.ts
- src/SldStyleParser.ts
was merged and released.
This PR is based on https://github.com/terrestris/geostyler-sld-parser/pull/170, which does not seem to be maintained anymore.
Added reading and writing `fontStyle` and `fontWeight` properties of `TextSymbolizer`. Updated tests accordingly. 
closes https://github.com/terrestris/geostyler/issues/916
> Parse fontStyle and fontWeight

- data/slds/line_graphicStroke.sld
- data/slds/line_simpleline.sld
- data/slds/point_simplecross.sld
- data/slds/point_simplepoint_filter.sld
- data/slds/point_simplepoint_nestedLogicalFilters.sld
- data/slds/point_simpleslash.sld
- data/slds/point_simplesquare.sld
- data/slds/point_simplestar.sld
- data/slds/point_simpletriangle.sld
- data/slds/point_simplex.sld
- package.json
- src/SldStyleParser.spec.ts
- src/SldStyleParser.ts
This PR introduces the `forceCasting` flag.
If set to `true` the SLDParser will try to cast all numeric or boolean like values to its datatypes.
Compare https://github.com/terrestris/geostyler-sld-parser/pull/127#issuecomment-486221366 for reference.
This also introduces the `ConstructorParams` type to allow setting `forceCasting`, `boolFilterFields`, and `numericFilterFields` when instantiating the parser.
> Introduces forceCasting flag

- data/slds/point_simplepoint_functionfilter.sld
- data/styles/point_simplepoint_functionfilter.ts
- package.json
- src/SldStyleParser.spec.ts
- src/SldStyleParser.ts
This introduces the parsing of the `strMatches` Function for SLDs.
@glenselle Would be nice if you could test if this suites all your need as described in #195 and in 
https://github.com/terrestris/geostyler/issues/996.
Closes #195
> Introduces parsing of strMatches FunctionFilter

- tslint.json
This removes the deprecated tslint rule `no-unused-variable`. Check [here](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#warning-deprecations) or https://github.com/palantir/tslint/issues/4046 for more information.
> Remove deprecated tslint rule "no-unused-variable"

- data/slds/point_externalgraphic_floatingPoint.sld
- data/styles/point_externalgraphic_floatingPoint.ts
- package.json
- src/SldStyleParser.spec.ts
- src/SldStyleParser.ts
Required for / fixes https://github.com/terrestris/geostyler/issues/995. The usage of `parseFloat` allows setting non-integer values.
The OGC SE specification also allows floating-point values for these attributes.
@terrestris/devs Please review
> Use parseFloat to parse symbolizer values

- data/slds/point_simpleLabel.sld
- data/styles/point_simpleLabel.ts
- src/SldStyleParser.spec.ts
- src/SldStyleParser.ts
Enables reading a sld label in the format of `<Label>myLabel</Label>` additionally to supported formats, such as `<Label><Literal>myLabel</Literal></Label>`.
However, we will face problems writing such labels, as from the current `geostyler-style` definition, we cannot distinguish in which of the above mentioned formats we should write to. Even though, it probably will not make a difference visually, this will lead to not being able to create the exactly same sld after reading and writing.
@KaiVolland do you have any suggestions, how we could solve that problem?
solves #266 
**Note:** With this PR we will only change reading a SLD and the writing will remain untouched due to above mentioned problem. Since there is no semantic difference in the output, all writes to SLD that contain a …
> enable parsing label without literal wrapper

- package.json
The urls in package.json still referenced the old repository on the terrestris organisation. This will be fixed in this PR.
Note: Referencing also works with the old urls, since github forwards them. However, this was done to have a cleaner project.
> Update deprecated urls in package.json

- data/slds/point_fontglyph.sld
- data/styles/point_fontglyph.ts
- src/SldStyleParser.spec.ts
- src/SldStyleParser.ts
This simply required not transforming to lowercase when writing SLD since the font name can contain uppercase characters, and these should be kept in order for GeoTools to be able to recognize the symbol.
The regexp to detect of a symbol is a font glyph was inspired by the one used in Geotools:
https://github.com/geotools/geotools/blob/b695b08d10499d3d670cfc94cda77de42134d1a0/modules/library/render/src/main/java/org/geotools/renderer/style/TTFMarkFactory.java#L68-L73
> Handle ttf:// format for symbols in mark symbolizers

- package-lock.json
- package.json
Packages `stream` and `timers` are required by `xml2js` but not in its depencies.
So we need to add them to our dependencies manually.
> Adds missing dependencies

- data/slds/1.0/point_styledLabel_elementOrder.sld
- data/slds/1.1/point_styledLabel_elementOrder.sld
- data/styles/point_styledLabel_elementOrder.ts
- src/SldStyleParser.ts
- src/SldStyleParser.v1.0.spec.ts
- src/SldStyleParser.v1.1.spec.ts
This preserves the order for all child elements of a parent node. Thereby, we can properly handle parts that are sensitive to ordering e.g. ordering of symbolizers, label templates.
To do so, I had to update the parser configuration. So that the structure of the parsed XML differs a little from the results of the previous configuration. More precisely, each parent node has a property `$$` which contains all child nodes as a list. There, each child node has a property `#name` that keeps the node name. Also, a node's value is now accessible under the `_` property.
I also updated the handling of label templates, which now works with all combinations of placeholders and literals.
> Preserve Order of XML Elements

- package-lock.json
- package.json
#5 removed the code that used `xmldom` and `@types/xmldom` devDependency but missed the `xmldom` dependency. I used node 12 to run `npm install`.
Since then, several PRs from automated tools kept the unused dependency up-to-date.
`xmldom@0.6.0` is vulnerable and can no longer be updated by the maintainers:
https://github.com/xmldom/xmldom/security/advisories/GHSA-5fg8-2547-mr8q
https://github.com/xmldom/xmldom/issues/271
So it's easier to finally drop the dependency than doing another upgrade.
> Drop xmldom from dependencies

- package-lock.json
- package.json
Updates the geostyler-style dependency.
https://github.com/geostyler/geostyler-style/pull/297
> Update geostyler-style dependency

- data/slds/1.0/point_simpleLabel2.sld
- data/slds/1.1/point_simpleLabel2.sld
- data/styles/point_simpleLabel2.ts
- src/SldStyleParser.ts
- src/SldStyleParser.v1.0.spec.ts
- src/SldStyleParser.v1.1.spec.ts
This fixes #524
The bug was caused by a falsly used plural on `CssParameter` and `SvgParameter`.
Some tests where added.
> Fix text fillcolor parsing

- data/slds/1.0/unsupported_properties.sld
- data/slds/1.1/unsupported_properties.sld
- data/styles/unsupported_properties.ts
- src/SldStyleParser.ts
- src/SldStyleParser.v1.0.spec.ts
- src/SldStyleParser.v1.1.spec.ts
This adds the `unsupportedProperties` to the `WriteStyleResult`.
> Adds unsupportedProperties feedback to WriteStyleResult

- src/SldStyleParser.ts
- src/SldStyleParser.v1.0.spec.ts
This fixes `checkForUnsupportedProperties` and extends the tests correspondingly.
> Fix `checkForUnsupportedProperties`

- .github/workflows/on-pull-request.yml
This adds an OS matrix to the `on-pull-request` workflow.
> Add OS matrix to PR workflow

- browser-build.config.js
- dev-build.config.js
This fixes the build on windows by using `path.join` in webpack configs.
> Fix build on windows

- src/SldStyleParser.ts
This removes falsly thrown errors.
Following the XSD of SLD a `<Stroke/>` element does not need to have any parameters:
Compare https://raw.githubusercontent.com/geoserver/geoserver/main/data/release/styles/pophatch.sld
This partially fixes this geostyler issue: https://github.com/geostyler/geostyler/issues/1867
> Remove false errors

- data/slds/1.0/raster_without_opacity.sld
- data/styles/raster_without_opacity.ts
- src/SldStyleParser.ts
- src/SldStyleParser.v1.0.spec.ts
Writing a parsed raster SLD without opacity (as added in this PR for the test) failed as the `sldRasterSymbolizer` (see diff) array contained an empty object in that scenario that lead to an error in the later processing.
This change fixes the problem.
Thx @dnlkoch for the help in debugging this.
Please check the type of change your PR introduces:
> fix: enable parsing of raster SLD without opacity

- .vscode/launch.json
- data/slds/1.1/point_externalgraphic_svg_displacement.sld
- data/slds/1.1/point_simplepoint_displacement.sld
- data/styles/point_externalgraphic_svg_displacement.ts
- data/styles/point_simplepoint_displacement.ts
- package-lock.json
- package.json
- src/SldStyleParser.ts
- src/SldStyleParser.v1.1.spec.ts
This adds support for reading and writing `Displacement` of the `Graphic` element.
The support is limited to SLD Version 1.1.0.
> Add support for graphic displacement

- data/slds/1.0/polygon_transparentpolygon.sld
- data/slds/1.1/polygon_transparentpolygon.sld
- data/styles/polygon_transparentpolygon.ts
- package-lock.json
- package.json
- src/SldStyleParser.ts
This adds `isNil` to many checks of property values to allow a value of `0`.
A test was adapated to demonstrate it.
This fixes #800
> Use lodash `isNil` for nullchecks

- data/slds/1.0/function_filter.sld
- data/slds/1.1/point_simplepoint_filter.sld
- data/slds/1.1/point_simplepoint_functionfilter.sld
- data/slds/1.1/point_simplepoint_nestedLogicalFilters.sld
- src/SldStyleParser.ts
The `ogc:` prefix for filters should be obsolete, since we are also setting the default namespace to ogc. This is the same for both supported SLD versions
> fix: remove unnecessary ogc: prefix from filter

- data/slds/1.0/text_lineplacement.sld
- data/slds/1.0/text_pointplacement.sld
- data/slds/1.1/text_lineplacement.sld
- data/slds/1.1/text_pointplacement.sld
- data/styles/geoserver/poi.ts
- data/styles/geoserver/poly_landmarks.ts
- data/styles/geoserver/pophatch.ts
- data/styles/geoserver/popshade.ts
- data/styles/geoserver/tiger_roads.ts
- data/styles/multi_simplelineLabel.ts
- data/styles/point_styledLabel_elementOrder.ts
- data/styles/point_styledLabel_literalOpenCurlyBraces.ts
- data/styles/point_styledLabel_literalPlaceholder.ts
- data/styles/point_styledlabel.ts
- data/styles/text_lineplacement.ts
- data/styles/text_pointplacement.ts
- src/SldStyleParser.geoserver.spec.ts
- src/SldStyleParser.ts
- src/SldStyleParser.v1.0.spec.ts
- src/SldStyleParser.v1.1.spec.ts
This adds support for label placements `point` and `line`.
> feat: read/write labelplacement

- .gitignore
- src/SldParser.spec.ts
- src/SldStyleParser.ts
- src/SldStyleParser.v1.0.spec.ts
- src/SldStyleParser.v1.1.spec.ts
For reading you can force sldVersion in option but it's not mandatory, it will be guessed, but for writing style, sldVersion is mandatory
> fix: Extract SLD version from SLD #696 and #925

- data/slds/1.0/cdata.sld
- data/styles/cdata.ts
- package-lock.json
- package.json
- src/SldParser.spec.ts
- src/SldStyleParser.ts
This fixes parsing of `<![CDATA[xxx]]>` values.
It removes the configured `cdataPropName` from the parser.
Closes #947 
@louwers i used your linked SLD for this test. If you don't want it to be in the repo just let me know and i will break it down to a simpler example and use this instead.
> Fix reading CDATA values from SLD

- data/styles/geoserver/poi.ts
- data/styles/geoserver/poly_landmarks.ts
- data/styles/geoserver/pophatch.ts
- data/styles/geoserver/popshade.ts
- data/styles/geoserver/tiger_roads.ts
- data/styles/multi_simplelineLabel.ts
- data/styles/point_simpleLabel.ts
- data/styles/point_styledLabel_literalPlaceholder.ts
- data/styles/point_styledlabel.ts
- data/styles/text_lineplacement.ts
- data/styles/text_pointplacement.ts
- src/SldStyleParser.ts
Fix #967 
Test if opacity value is undefined or null, but not 0.
> fix: Test if opacity is realy undefined

- src/SldStyleParser.ts
> Fix generate Format tag

- data/slds/1.0/function_filter_property_to_property.sld
- data/slds/1.1/function_filter_property_to_property.sld
- data/styles/function_filter_property_to_property.ts
- src/SldStyleParser.ts
- src/SldStyleParser.v1.0.spec.ts
- src/SldStyleParser.v1.1.spec.ts
Allow https://github.com/geostyler/geostyler-openlayers-parser to handle property to property comaprison fiilters by parsing filter args into geostyler functions.
```
<ogc:Filter>
<ogc:PropertyIsEqualTo> 
<ogc:PropertyName>NAME</ogc:PropertyName> 
<ogc:PropertyName>TITLE</ogc:PropertyName>
</ogc:PropertyIsEqualTo> 
</ogc:Filter>
```
```
[
==,
{
name: 'property',
args: ['NAME']
}
{
name: 'property',
args: ['TITLE']
}
]
```
For more details see #974
> Property to property comparison

- data/slds/geoserver/pattern_polygon_alternative_margin.sld
- src/SldStyleParser.geoserver.spec.ts
- src/SldStyleParser.ts
> fix: support spaces as sperator for vendor-option graphic-margin
